### ISSUE TITLE
About the predict.py

### ISSUE THREAD

**Issue by zhangconghhh** [NTech-Lab/deepfake-detection-challenge#1]
Hello, when I run the predict.py, there is something wrong with the code. It seems like the input size is not matching.
![image](https://user-images.githubusercontent.com/23146227/85288499-66d64a00-b4c8-11ea-8d9f-3d41aa6a5020.png)

**Comment by azat-d** [comment]
Hi Cong Zhang,
The problem may be in the wrong version of the torchvision library. I used version v0.4.1. Please see the Dockerfile for the exact environment.
